# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON'
  pod 'SDWebImage', '~> 5.0'
  # Pods for ImageViewer

  target 'ImageViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageViewerUITests' do
    # Pods for testing
  end

end
